version: '2.3'

services:
  mining-pool-api:
    build: .
    ports:
      - 9090:9090
    environment:
      DATABASE_URL: #postgres_db_url
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    hostname: postgres-docker
    expose:
      - 5432
    environment:
      POSTGRES_USER: #postgres
      POSTGRES_PASSWORD: #password
      POSTGRES_DB: mining_pool_api
    volumes:
      - ./migrations/2022-12-16-122550_mining_pool_api/up.sql:/docker-entrypoint-initdb.d/up.sql